<h1 style="text-align:center" >TP 1 TDM</h1>

## importation du bibliotheque

In [1]:
import numpy as np # pour la manupilation du matrice
from PIL import Image # pour la manupilation des images 

# EX1: compression par encodage RLE

<p style="font-size : 16px;">RLE "Run-Length Encoding". Il s’agit d’un algorithme de compression sans perte simple qui est souvent utilisé pour compresser des données qui contiennent de longues séries de la même valeur </p>

## ces fonctions pour facilite le calculer du occurrence du symbole successive dans les matrices d'images

 <p style="font-size : 16px;"> cette fonction permet de de convertir une matrice a une seule vecteur (ligne a coter de l'autre)</p>

In [13]:
def toligne(array) :
    return array.ravel();

 <p style="font-size : 16px;"> cette fonction permet de de convertir une matrice a une seule vecteur (coloune a coter de l'autre)</p>

In [14]:
def toColoums(array) :
    liste=[array[:,i] for i in range(array[0].size)]
    return np.array(liste).ravel();

 <p style="font-size : 16px;"> cette fonction permet de de convertir une matrice a une seule vecteur par une methode de zigzag</p>

In [50]:

def zigzag(input):
    h, w = input.shape
    output = [0] * (h * w)
    i = 0
    j = 0
    for k in range(h * w):
        output[k] = input[i][j]
        if (i + j) % 2 == 0:
            if j == w - 1:
                i += 1
            elif i == 0:
                j += 1
            else:
                i -= 1
                j += 1
        else:
            if i == h - 1:
                j += 1
            elif j == 0:
                i += 1
            else:
                i += 1
                j -= 1
    return np.array(output);


input_matrix = np.array([[1,2,3,44],[4,5,6,66],[7,8,9,99]])
output_list = zigzag(input_matrix)

print(output_list)


[ 1  2  4  7  5  3 44  6  8  9 66 99]


autre methode de zigzage

In [66]:
def zigzag2(input):
    h, w = input.shape
    size = h + w - 1
    output = np.zeros((size,min(size,h)), dtype=input.dtype)
    output+=5000
    for i in range(h):
        for j in range(w):
            output[i+j, i] = input[i, j]
    
    output=output.ravel()
    output=np.delete(output,np.where(output == 5000))
    return output;

# Example usage
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 255]])
zigzag_arr = zigzag2(arr)
print(zigzag_arr)


[  1   2   4   3   5   7   6   8 255]


## functions

In [67]:
def arrayToBinary(array) : #array 1 dim
    # convert each element of the array to binary
    binary_arr = [np.binary_repr(x, width=8) for x in array]
    return np.array(binary_arr);

In [68]:
arrayToBinary(zigzag_arr)

array(['00000001', '00000010', '00000100', '00000011', '00000101',
       '00000111', '00000110', '00001000', '11111111'], dtype='<U8')

In [34]:
def concatinateBinaryArray(binaryArray) :
    chr1 = ''
    for elem in binaryArray :
        #print(elem)
        chr1+=elem
    return chr1;

In [107]:
def concatinateBinaryArray2(binaryArray) :
    chr1 = ''
    for elem in binaryArray :
        #print(elem)
        chr1+=str(elem)
    return chr1;

In [37]:
chr1=concatinateBinaryArray(arrayToBinary(zigzag_arr))

### reverse function

<p style="font-size : 16px;">cette fonction convertir une chaine binaire a une liste du chaine binaire   </p>

In [89]:
def binaryStrToArray(chaine) :
    liste=[chaine[i:i+8] for i in range(0,len(chaine),8) ]
    return np.array(liste);

<p style="font-size : 16px;">la chaine binaire   </p>

In [76]:
chr1

'000000010000001000000100000000110000010100000111000001100000100000001001'

In [44]:
binaryStrToArray(chr1)

array(['00000001', '00000010', '00000100', '00000011', '00000101',
       '00000111', '00000110', '00001000', '00001001'], dtype='<U8')

<p style="font-size : 16px;">cette fonction permet de convertir une liste du chaine binaire au une liste du nbr dicimal </p>

In [93]:
def binaryToDicimal(binaryList) :
    decimal_array = [int(binary,2) for binary in binaryList]
    return np.array(decimal_array);

In [75]:
binaryToDicimal(binaryStrToArray(chr1))

[1, 2, 4, 3, 5, 7, 6, 8, 9]

<p style="font-size : 16px;">cette fonction calcule l'enverse du vecteur zigzager  </p>

In [45]:
def reverse_zigzag(zigzag, h, w):
    output = np.zeros((h, w), dtype=zigzag.dtype)
    i = 0
    j = 0
    for k in range(len(zigzag)):
        output[i][j] = zigzag[k]
        if (i + j) % 2 == 0:
            if j == w - 1:
                i += 1
            elif i == 0:
                j += 1
            else:
                i -= 1
                j += 1
        else:
            if i == h - 1:
                j += 1
            elif j == 0:
                i += 1
            else:
                i += 1
                j -= 1
    return output


In [51]:
reverse_zigzag(output_list,3,4)

array([[ 1,  2,  3, 44],
       [ 4,  5,  6, 66],
       [ 7,  8,  9, 99]])

## Question 1 : calcule du frequence d'occurrence

In [2]:
phrase="aaaaaabbbeeeee" #    <p style="font-size : 16px;"> </p>

<p style="font-size : 16px;"> cette fonction retourne une liste des tuples(symbole,occurance) pour chaque symbole </p>

In [3]:
def freqOccurance(phrase) :
    count =1
    liste=[]
    for i in range(len(phrase)) :
        if i != len(phrase)-1:
            if phrase[i]==phrase[i+1] :
                count+=1
            else :
                tupl=phrase[i],count
                liste.append(tupl)
                count =1
    tupl=phrase[i],count
    liste.append(tupl)
    return liste;

In [4]:
freqOccurance(phrase)

[('a', 6), ('b', 3), ('e', 5)]

## Question 2 : Evalue le code RLE

<p style="font-size : 16px;"> Cacule du gain </p>

In [5]:
def evalueRLE(phrase) :
    lenCodageRLE=len(freqOccurance(phrase))*2
    lenData=len(phrase)
    return (lenData-lenCodageRLE)/lenData;

In [7]:
evalueRLE(phrase)

0.5714285714285714

## Question 3 : taux de compression

In [9]:
def taux(data) :
    lenCodageRLE=len(freqOccurance(data))*2
    lenData=len(data)
    return lenCodageRLE/lenData;

In [10]:
taux(phrase)

0.42857142857142855

## Question 4  : Decodage

In [11]:
def decodage(codageRle):
    phrs=""
    for tupl in codageRle:
        for i in range(tupl[1]) :
            phrs+=tupl[0]
    return phrs;

In [12]:
decodage(freqOccurance(phrase))

'aaaaaabbbeeeee'

# Application du ex1 

In [78]:
zero = np.zeros(11,dtype='int')
one = np.ones(11,dtype='int')
im = np.array([one,one,one,zero,zero,zero,zero,one,one,one,one,zero,zero,one,one])

In [79]:
im

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

metter la matrice a une seule veceur

In [81]:
vecteur = toligne(im)
vecteur

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [116]:
"""if np.max(vecteur) >1 :"""
binaryList=arrayToBinary(vecteur)
    
"""else :
    binaryList=concatinateBinaryArray2(vecteur)"""

'else :\n    binaryList=concatinateBinaryArray2(vecteur)'

In [117]:
chaineBinary=concatinateBinaryArray(binaryList)

In [118]:
listeRLE=freqOccurance(chaineBinary)

In [119]:
evalueRLE(chaineBinary)

0.7

In [120]:
taux(chaineBinary)

0.3

In [121]:
decodeRLE=decodage(listeRLE)

In [122]:
convertedBinaryList=binaryStrToArray(decodeRLE)

In [123]:
binaryToDicimal(convertedBinaryList)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])